### ISSUE TITLE
500 error handshake failure

### ISSUE THREAD

**Issue by simon-brooke** [gja/pwa-clojure#1]
Running **lein run** starts an HTTP listener on port 3000, but connecting to that listener returns the following error to the browser:

```
HTTP ERROR: 500

Problem accessing /. Reason:

    Received fatal alert: handshake_failure
Powered by Jetty://
```

Looking at the stacktrace it seems the server is expecting an HTTPS connection:

```
simon@fletcher:~/workspace/pwa-clojure$ lein run
2017-05-23 15:17:08.830:INFO::main: Logging initialized @702ms
2017-05-23 15:17:12.255:INFO:oejs.Server:main: jetty-9.2.10.v20150310
2017-05-23 15:17:12.276:INFO:oejs.ServerConnector:main: Started ServerConnector@6c9e7af2{HTTP/1.1}{0.0.0.0:3000}
2017-05-23 15:17:12.277:INFO:oejs.Server:main: Started @4148ms
2017-05-23 15:20:39.698:WARN:oejs.HttpChannel:qtp980801953-18: /
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:553)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:412)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:328)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at clj_http.core$request.invokeStatic(core.clj:304)
	at clj_http.core$request.invoke(core.clj:208)
	at clojure.lang.Var.invoke(Var.java:379)
	at clj_http.client$wrap_request_timing$fn__9422.invoke(client.clj:835)
	at clj_http.headers$wrap_header_map$fn__7729.invoke(headers.clj:143)
	at clj_http.client$wrap_query_params$fn__9325.invoke(client.clj:661)
	at clj_http.client$wrap_basic_auth$fn__9332.invoke(client.clj:677)
	at clj_http.client$wrap_oauth$fn__9336.invoke(client.clj:687)
	at clj_http.client$wrap_user_info$fn__9341.invoke(client.clj:700)
	at clj_http.client$wrap_url$fn__9408.invoke(client.clj:801)
	at clj_http.client$wrap_redirects$fn__9107.invoke(client.clj:267)
	at clj_http.client$follow_redirect.invokeStatic(client.clj:241)
	at clj_http.client$follow_redirect.invoke(client.clj:230)
	at clj_http.client$wrap_redirects$fn__9107.invoke(client.clj:288)
	at clj_http.client$wrap_decompression$fn__9132.invoke(client.clj:339)
	at clj_http.client$wrap_input_coercion$fn__9262.invoke(client.clj:518)
	at clj_http.client$wrap_additional_header_parsing$fn__9283.invoke(client.clj:552)
	at clj_http.client$wrap_output_coercion$fn__9253.invoke(client.clj:468)
	at clj_http.client$wrap_exceptions$fn__9093.invoke(client.clj:219)
	at clj_http.client$wrap_accept$fn__9297.invoke(client.clj:595)
	at clj_http.client$wrap_accept_encoding$fn__9303.invoke(client.clj:609)
	at clj_http.client$wrap_content_type$fn__9292.invoke(client.clj:585)
	at clj_http.client$wrap_form_params$fn__9386.invoke(client.clj:765)
	at clj_http.client$wrap_nested_params$fn__9403.invoke(client.clj:790)
	at clj_http.client$wrap_method$fn__9346.invoke(client.clj:707)
	at clj_http.cookies$wrap_cookies$fn__6679.invoke(cookies.clj:124)
	at clj_http.links$wrap_links$fn__7966.invoke(links.clj:51)
	at clj_http.client$wrap_unknown_host$fn__9412.invoke(client.clj:810)
	at clj_http.client$get.invokeStatic(client.clj:913)
	at clj_http.client$get.doInvoke(client.clj:909)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at pwa_clojure.server.data$characters.invokeStatic(data.clj:31)
	at pwa_clojure.server.data$characters.invoke(data.clj:29)
	at pwa_clojure.server.data$load_data.invokeStatic(data.clj:47)
	at pwa_clojure.server.data$load_data.invoke(data.clj:45)
	at pwa_clojure.views$pwa_page.invokeStatic(views.clj:39)
	at pwa_clojure.views$pwa_page.invoke(views.clj:37)
	at pwa_clojure.app$pwa_route_handler$fn__9599.invoke(app.clj:11)
	at bidi.ring$eval1477$fn__1478.invoke(ring.clj:20)
	at bidi.ring$eval1456$fn__1457$G__1447__1466.invoke(ring.clj:12)
	at pwa_clojure.server.bidi_handler$make_bidi_handler$fn__1625.invoke(bidi_handler.clj:16)
	at pwa_clojure.server.bidi_handler$make_bidi_handler$fn__1625.invoke(bidi_handler.clj:22)

```

It would be really nice to have something in the README saying 'this is how to get the project up and running'

Cheers

Simon

**Comment by radirk** [comment]
Don't know the cause, but upgrading clj-http helped:
[clj-http "3.6.0"]

**Comment by gja** [comment]
@simon-brooke are you trying to do https? This won't support https on localhost.

**Comment by gja** [comment]
Chrome does support pwa without https on localhost (just fyi)

**Comment by simon-brooke** [comment]
Thanks, guys. That works.
